### ISSUE TITLE
Get some synergy with firebaseopensource.com

### ISSUE THREAD

**Issue by anishkny** [jthegedus/awesome-firebase#31]
**What is it that you wish to discuss?**

https://firebaseopensource.com showcases great open source libraries/samples/demos related to Firebase - which overlaps with awesome-firebase. I wonder if we can get some synergy going betwixt the two!

**Additional context**

https://github.com/firebase/firebaseopensource.com/issues/110

**Comment by jthegedus** [comment]
As a consumer it would be good to have single place to find everything new. However I think the two projects serve different goals. Because of the ubiquity of awesome lists and the lack of an up to date Firebase one I decided to create this. The other project isn't necessarily easily discover-able for those searching for `awesome firebase`.

Do you have any suggestions? What type of synergy would you like to see (aside from me just mirroring PRs to the other repo)?

**Comment by anishkny** [comment]
Honestly I just wanted to raise the discussion - but don't have any concrete suggestions. If there was a way to single source at least part of one (or the other)...

**Comment by jthegedus** [comment]
Fair enough. Single sourcing would be good for people who want to display their projects on both sites. For that to occur though we would need to determine the criteria to add projects to the list.

**Comment by anishkny** [comment]
FWIW, firebaseopensource.com seems to maintain list of featured/useful/interesting projects here:

https://github.com/firebase/firebaseopensource.com/blob/master/config/additional_projects.json

```js
{
  "projects": [
    "angular::angularfire2",
    "googlesamples::easypermissions",
    "tylermcginnis::re-base",
    // and so on ...
  ]
}
```

**Comment by jthegedus** [comment]
Thanks for the information @anishkny I will think on this some more and see if I can come up with some concrete solutions for single-sourcing. In the meantime, if you come up with any ideas please share them with me here or in the other issue you opened :smiley:
